[package]
name = "agupd"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
libc = { workspace = true }

[[bin]]
name = "agupd"
path = "src/main.rs"
